urg_node2:
  ros__parameters:
    ip_address: '192.168.1.10'
    ip_port: 10940
    frame_id : 'lidar_link'
    calibrate_time : false
    synchronize_time : false
    publish_intensity : false
    publish_multiecho : false
    error_limit : 4
    error_reset_period : 5.0
    diagnostics_tolerance : 0.05
    diagnostics_window_time : 5.0
    time_offset : 0.0
    angle_min : -1.57
    angle_max : 1.57
    skip : 0
    cluster : 1
